# Generated by Django 4.2.16 on 2024-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.BigIntegerField(unique=True)),
                ("login_id", models.CharField(blank=True, max_length=15, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("closed_time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("Technical", "Technical"),
                            ("Payment", "Payment"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("attachment", models.BinaryField(blank=True, null=True)),
                ("assigned_to", models.JSONField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Closed", "Closed")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "levels",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")],
                        null=True,
                    ),
                ),
                ("attribute1", models.TextField(blank=True, null=True)),
                ("attribute2", models.TextField(blank=True, null=True)),
                ("attribute3", models.TextField(blank=True, null=True)),
                ("attribute4", models.TextField(blank=True, null=True)),
                ("attribute5", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "tickets",},
        ),
    ]
