# Generated by Django 5.1.4 on 2024-12-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='General', max_length=255)),
                ('question_number', models.IntegerField(default=1)),
                ('question', models.TextField(default='')),
                ('option1', models.TextField(default='')),
                ('efficiency_1', models.IntegerField(default=0)),
                ('description_1', models.TextField(default='')),
                ('option2', models.TextField(default='')),
                ('efficiency_2', models.IntegerField(default=0)),
                ('description_2', models.TextField(default='')),
                ('option3', models.TextField(default='')),
                ('efficiency_3', models.IntegerField(default=0)),
                ('description_3', models.TextField(default='')),
                ('option4', models.TextField(default='')),
                ('efficiency_4', models.IntegerField(default=0)),
                ('description_4', models.TextField(default='')),
                ('correct_option', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'costcuttingquestions',
            },
        ),
    ]
