# Generated by Django 5.1.2 on 2024-12-24 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bannerupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.FileField(blank=True, null=True, upload_to='banner/')),
                ('banner2', models.FileField(blank=True, null=True, upload_to='banner/')),
                ('banner3', models.FileField(blank=True, null=True, upload_to='banner/')),
            ],
            options={
                'db_table': 'internbanner',
            },
        ),
        migrations.CreateModel(
            name='collegeRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phonenumber', models.CharField(max_length=15)),
                ('College_name', models.CharField(max_length=50)),
                ('Address_line_1', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=6)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('ep1', models.CharField(blank=True, max_length=300, null=True)),
                ('ep2', models.CharField(blank=True, max_length=300, null=True)),
                ('ep3', models.CharField(blank=True, max_length=300, null=True)),
                ('ep4', models.CharField(blank=True, max_length=300, null=True)),
                ('ep5', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'College_Registartion',
            },
        ),
        migrations.CreateModel(
            name='commonquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=35, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_input', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_output', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_output', models.CharField(blank=True, max_length=250, null=True)),
                ('posted_on', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'common_challenge_questions',
            },
        ),
        migrations.CreateModel(
            name='commonquestionanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_created=True)),
                ('question_gid', models.CharField(blank=True, max_length=35, null=True)),
                ('user_id', models.CharField(blank=True, max_length=35, null=True)),
                ('token', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'common_challenge_answers_submitted',
            },
        ),
        migrations.CreateModel(
            name='CostCuttingCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy_name', models.CharField(default='General Category', max_length=50)),
                ('category_image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'costcuttingcategorymaster',
            },
        ),
        migrations.CreateModel(
            name='dailyquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=35, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_input', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_output', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_output', models.CharField(blank=True, max_length=250, null=True)),
                ('posted_on', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'Daily_challenge_questions',
            },
        ),
        migrations.CreateModel(
            name='dailyquestionanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_created=True)),
                ('question_gid', models.CharField(blank=True, max_length=35, null=True)),
                ('user_id', models.CharField(blank=True, max_length=35, null=True)),
                ('token', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'Daily_challenge_answers_submitted',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departmentmaster',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('current_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('government', 'Government Worker')], max_length=15)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('epf_number', models.CharField(blank=True, max_length=22, null=True)),
                ('facebook_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('about_you', models.TextField(blank=True, null=True)),
                ('house_no', models.CharField(max_length=100)),
                ('area_street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=6)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('service', 'Service'), ('manufacturing', 'Manufacturing')], max_length=15, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed_out_year', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('micr_code', models.CharField(max_length=9)),
                ('account_number', models.CharField(max_length=18)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
                ('resume', models.BinaryField(blank=True, null=True)),
                ('pan_card', models.BinaryField(blank=True, null=True)),
                ('aadhar_card', models.BinaryField(blank=True, null=True)),
                ('bank_passbook', models.BinaryField(blank=True, null=True)),
                ('attribute1', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instructorMaster',
            },
        ),
        migrations.CreateModel(
            name='IssueTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'issue_type_master',
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Team ID')),
                ('team_category', models.CharField(max_length=50, unique=True, verbose_name='Team Category')),
            ],
            options={
                'db_table': 'team_category',
            },
        ),
        migrations.CreateModel(
            name='Userauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_authenthication',
            },
        ),
        migrations.CreateModel(
            name='weeklyquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=35, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_input', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_output', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_output', models.CharField(blank=True, max_length=250, null=True)),
                ('posted_on', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'weekly_challenge_questions',
            },
        ),
        migrations.CreateModel(
            name='weeklyquestionanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_created=True)),
                ('question_gid', models.CharField(blank=True, max_length=35, null=True)),
                ('user_id', models.CharField(blank=True, max_length=35, null=True)),
                ('token', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'weekly_challenge_answers_submitted',
            },
        ),
    ]
