# Generated by Django 5.1.3 on 2025-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'designationmaster',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('father_husband_name', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('department', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('finance', 'Finance'), ('admin', 'Admin')], max_length=50)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('executive', 'Executive'), ('analyst', 'Analyst'), ('assistant', 'Assistant')], max_length=50)),
                ('employee_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('uan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(max_length=10)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('education_qualification', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=100)),
                ('date_of_join', models.DateField()),
                ('upload_photo', models.ImageField(upload_to='employee_photos/')),
                ('house_no', models.CharField(max_length=100)),
                ('area_street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=6)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('micr_code', models.CharField(max_length=9)),
                ('account_number', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'employeetypemaster',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
