# Generated by Django 5.1.3 on 2025-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.CharField(blank=True, max_length=35, null=True)),
                ('statement_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name_of_innovator', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('highest_education_qualification', models.CharField(max_length=255)),
                ('title_of_project', models.CharField(max_length=255)),
                ('name_of_product', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('uniqueness', models.TextField(default='')),
                ('innovation_type', models.CharField(choices=[('new', 'New'), ('upgrade', 'Upgrade')], default='new', max_length=50)),
                ('existing_product_upgrade', models.TextField(blank=True, null=True)),
                ('need', models.TextField(default='')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_advantage', models.TextField(default='')),
                ('social_impact', models.TextField(default='')),
                ('proposal_file', models.BinaryField()),
                ('problem_statement_id', models.IntegerField(blank=True, null=True)),
                ('attribute1', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ideasubmissions',
            },
        ),
        migrations.CreateModel(
            name='statementshowcasecategoryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementcategory', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'dynamic_statement_showcase_category',
            },
        ),
        migrations.CreateModel(
            name='statementshowcaseform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=40)),
                ('statement', models.CharField(max_length=5000)),
                ('statementcategory', models.CharField(max_length=250)),
                ('at1', models.CharField(max_length=250)),
                ('at2', models.CharField(max_length=250)),
                ('at3', models.CharField(max_length=250)),
                ('at4', models.CharField(max_length=250)),
                ('at5', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'dynamic_statemnt_showcase',
            },
        ),
    ]
