# Generated by Django 5.1.3 on 2025-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_remove_student_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=255)),
            ],
        ),
    ]
