# Generated by Django 4.1.9 on 2025-01-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_internregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternRegistration',
        ),
    ]
