# Generated by Django 5.1.5 on 2025-02-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_internregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternRegistration',
        ),
    ]
