# Generated by Django 5.1.5 on 2025-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventsimage',
            },
        ),
    ]
